inherit_gem:
  theforeman-rubocop:
    - strict.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: 111 # TODO: discuss and set this

Naming/MethodParameterName:
  MinNameLength: 2

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false
